#!/bin/bash
# DO NOT EDIT THIS FILE

TARGETS="main.cmo test.cmo"

ocamlbuild -use-ocamlfind $TARGETS
if [[ $? -ne 0 ]]; then
  cat <<EOF
===========================================================
WARNING

Our code currently does not compile.  This is very bad.
Please try to fix it asap.
===========================================================
EOF
  exit 1
fi

if ocamlbuild -use-ocamlfind checktypes.cmo ; then
  cat <<EOF
===========================================================
Your function names and types are working as intended.
Congratulations!
===========================================================
EOF
else
  cat <<EOF
===========================================================
WARNING

Your function names and types are broken. This is very bad.
Please try to fix it asap.
===========================================================
EOF
fi